### ISSUE TITLE
Fehlermeldung bei "building for production."

### ISSUE THREAD

**Issue by frankdema** [hikaru90/barebones-vite-tailwind-starter#1]
Hallo, 
ich wollte Ihr Starter Projekt nutzen. 

 "npm run dev" --> geht.

wenn ich aber sage:
"npm run build" bekomme ich eine Fehlermeldung (Siehe Bild)

<img width="1153" alt="Bildschirmfoto 2022-09-07 um 10 10 14" src="https://user-images.githubusercontent.com/77227123/188826124-c9ba477a-7fee-4649-9e70-eca1601d52bc.png">

Haben Sie eine Idee, wie ich das lösen kann?

Mit freundlichen Grüßen

Frank

**Comment by hikaru90** [comment]
Hi Frank,
Ich habe leider gerade keinen Rechner zur Hand, aber ich habe diesen Link gefunden: [https://stackoverflow.com/questions/66863200/changing-the-input-and-output-directory-in-vite](https://stackoverflow.com/questions/66863200/changing-the-input-and-output-directory-in-vite) 
Das klingt nach deinem Problem. Folgendes sieht vielversprechend aus:

`module.exports = {
  root: 'src',
  build: {
    outDir: '../dist'
  }
}`

Ich hoffe, dass das hilft.
Liebe Grüße
Alex

**Comment by frankdema** [comment]
Ja, vielen Dank für die schnelle Hilfe


vite.config.js
```
/**
 * @type {import('vite').UserConfig}
 */

 const config = {
  root: 'src/',
  build: {
    outDir: '../dist'
}
}

export default config
```
